### ISSUE TITLE
As a user I want the app to react to my tapping on a surface

### ISSUE THREAD

**Issue by yashBhosale** [ItsNotRick/COP4331#16]

**Comment by ItsNotRick** [comment]
Test Procedure:
Complete the other microphone related tests first.
Lay the phone on a table and slap the table, a row of asterisks should appear for just a moment.
If the asterisks are always there: raise the threshold until they're not.
If the asterisks never appear: lower the threshold until they appear from a moderate slap.

If there isn't a threshold setting that allows for the asterisks to appear from a moderate slap the test fails.
